// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_get_100000_coins = "CgkIh_WGrpkCEAIQAg"; // <GPGSID>
        public const string achievement_unlock_all_environments = "CgkIh_WGrpkCEAIQBg"; // <GPGSID>
        public const string achievement_1000_distance_covered = "CgkIh_WGrpkCEAIQBw"; // <GPGSID>
        public const string achievement_unlock_all_cars = "CgkIh_WGrpkCEAIQBQ"; // <GPGSID>
        public const string achievement_use_50_shields = "CgkIh_WGrpkCEAIQDA"; // <GPGSID>
        public const string achievement_get_10000_coins = "CgkIh_WGrpkCEAIQAQ"; // <GPGSID>
        public const string achievement_unlock_2nd_environement = "CgkIh_WGrpkCEAIQAw"; // <GPGSID>
        public const string achievement_5000_distance_covered = "CgkIh_WGrpkCEAIQCA"; // <GPGSID>
        public const string achievement_10000_distance_covered = "CgkIh_WGrpkCEAIQCQ"; // <GPGSID>
        public const string achievement_unlock_2nd_car = "CgkIh_WGrpkCEAIQBA"; // <GPGSID>
        public const string leaderboard_road_draw_leaders = "CgkIh_WGrpkCEAIQAA"; // <GPGSID>
        public const string achievement_use_50_slow_moo = "CgkIh_WGrpkCEAIQCw"; // <GPGSID>
        public const string achievement_use_100_boost = "CgkIh_WGrpkCEAIQCg"; // <GPGSID>

}

